// ============================================================================
// PLACEHOLDER FILE - DO NOT USE AS-IS
// ============================================================================
// This file is normally auto-generated by running:
//     flutterfire configure
// in the root of this project, after creating a Firebase project at
// https://console.firebase.google.com and enabling Authentication
// (Email/Password) and Cloud Firestore.
//
// I cannot generate real values here because they are unique to YOUR
// Firebase project (API keys, app IDs, etc. tied to your account).
// Follow README.md Step 3 to replace this entire file automatically.
// ============================================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured yet. '
        'Run `flutterfire configure` - see README.md Step 3.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured yet. '
          'Run `flutterfire configure` - see README.md Step 3.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` - see README.md Step 3.',
        );
    }
  }
}
